const fs = require('fs');
const path = require('path');

const outputDir = path.join(__dirname, 'src', 'data', 'mbbs');
fs.mkdirSync(outputDir, { recursive: true });

// ============================================================
// ANATOMY — BD Chaurasia, Snell, KLM
// ============================================================
const anatomyMCQs = [
  // --- UPPER LIMB ---
  { id: 'ana_1', text: 'The clavicle articulates medially with which bone?', options: ['Scapula', 'Manubrium of sternum', 'First rib', 'Coracoid process'], correct: 1, explanation: 'The clavicle articulates medially with the manubrium of the sternum at the sternoclavicular joint, the only bony articulation of the upper limb with the axial skeleton.', difficulty: 'easy' },
  { id: 'ana_2', text: 'The "anatomical snuffbox" is bounded anteriorly by the tendon of:', options: ['Extensor pollicis brevis', 'Extensor pollicis longus', 'Abductor pollicis longus', 'Flexor pollicis longus'], correct: 0, explanation: 'The anatomical snuffbox is bounded anteriorly (radially) by the tendons of abductor pollicis longus and extensor pollicis brevis, and posteriorly (ulnarly) by extensor pollicis longus.', difficulty: 'medium' },
  { id: 'ana_3', text: 'A patient presents with inability to abduct the arm beyond 15 degrees. Which nerve is most likely injured?', options: ['Radial nerve', 'Musculocutaneous nerve', 'Axillary nerve', 'Long thoracic nerve'], correct: 2, explanation: 'The axillary nerve supplies the deltoid (main abductor of arm). Loss of axillary nerve function results in inability to abduct arm beyond the first 15 degrees (supraspinatus initiates first 15°).', difficulty: 'hard' },
  { id: 'ana_4', text: 'The brachial plexus arises from which spinal cord segments?', options: ['C4-C8', 'C5-T1', 'C4-T2', 'C6-T1'], correct: 1, explanation: 'The brachial plexus arises from the ventral rami of spinal nerve roots C5, C6, C7, C8, and T1.', difficulty: 'easy' },
  { id: 'ana_5', text: 'Wrist drop is caused by injury to which nerve?', options: ['Median nerve', 'Ulnar nerve', 'Radial nerve', 'Axillary nerve'], correct: 2, explanation: 'Wrist drop (inability to extend the wrist) is caused by radial nerve injury. The radial nerve supplies the extensors of the forearm.', difficulty: 'easy' },
  { id: 'ana_6', text: 'Which muscle is responsible for opposition of the thumb?', options: ['Abductor pollicis brevis', 'Flexor pollicis brevis', 'Opponens pollicis', 'Adductor pollicis'], correct: 2, explanation: 'Opponens pollicis, a thenar muscle supplied by the recurrent branch of median nerve, is the primary muscle responsible for thumb opposition.', difficulty: 'medium' },
  { id: 'ana_7', text: '"Claw hand" deformity is most pronounced in which nerve injury?', options: ['Median nerve at wrist', 'Ulnar nerve at wrist', 'Radial nerve at elbow', 'Musculocutaneous nerve'], correct: 1, explanation: 'Ulnar nerve injury at the wrist causes "claw hand" deformity affecting ring and little fingers (4th and 5th digits) due to loss of lumbrical action with intact FDP.', difficulty: 'medium' },
  { id: 'ana_8', text: 'The contents of the carpal tunnel include all of the following EXCEPT:', options: ['Flexor digitorum superficialis tendons', 'Flexor pollicis longus tendon', 'Ulnar nerve', 'Median nerve'], correct: 2, explanation: 'The carpal tunnel contains the median nerve, 4 tendons of FDS, 4 tendons of FDP, and FPL tendon. The ulnar nerve passes superficial to the flexor retinaculum through Guyon\'s canal.', difficulty: 'hard' },
  { id: 'ana_9', text: 'Erb\'s palsy results from damage to which roots of brachial plexus?', options: ['C5, C6', 'C7, C8', 'C8, T1', 'C5, T1'], correct: 0, explanation: 'Erb\'s palsy results from damage to C5 and C6 roots (upper trunk). Clinically presents as "waiter\'s tip" position with arm adducted, medially rotated, and forearm pronated.', difficulty: 'medium' },
  { id: 'ana_10', text: 'A patient cannot flex the terminal phalanx of the index finger. Which muscle is paralyzed?', options: ['Flexor digitorum superficialis', 'Lumbrical', 'Flexor digitorum profundus', 'Flexor carpi radialis'], correct: 2, explanation: 'Flexor digitorum profundus (FDP) flexes the distal interphalangeal joint. For the index and middle fingers, FDP is supplied by the anterior interosseous nerve (branch of median nerve).', difficulty: 'hard' },

  // --- LOWER LIMB ---
  { id: 'ana_11', text: 'The femoral triangle is bounded superiorly by:', options: ['Poupart\'s ligament (inguinal ligament)', 'Sartorius', 'Adductor longus', 'Iliopsoas'], correct: 0, explanation: 'The femoral triangle is bounded: superiorly by inguinal ligament, medially by adductor longus, and laterally by sartorius. Floor: iliopsoas and pectineus.', difficulty: 'easy' },
  { id: 'ana_12', text: 'The order of structures in the femoral triangle from lateral to medial is:', options: ['Vein, Artery, Nerve', 'Nerve, Artery, Vein', 'Artery, Vein, Nerve', 'Nerve, Vein, Artery'], correct: 1, explanation: 'From lateral to medial, the contents of the femoral sheath are: Nerve (lateral, outside sheath), Artery, Vein. Mnemonic: NAVY (Nerve, Artery, Vein, Y-fronts/lymphatics).', difficulty: 'easy' },
  { id: 'ana_13', text: 'The nerve most commonly injured in a posterior dislocation of the hip joint is:', options: ['Obturator nerve', 'Femoral nerve', 'Sciatic nerve', 'Superior gluteal nerve'], correct: 2, explanation: 'The sciatic nerve runs posterior to the hip joint and is the most commonly injured nerve in posterior dislocation of the hip, presenting with foot drop.', difficulty: 'medium' },
  { id: 'ana_14', text: 'Foot drop is caused by damage to which nerve?', options: ['Tibial nerve', 'Common peroneal (fibular) nerve', 'Femoral nerve', 'Sural nerve'], correct: 1, explanation: 'Common peroneal nerve damage causes foot drop (inability to dorsiflex the foot) as it supplies the anterior and lateral compartments of the leg. It is vulnerable at the neck of the fibula.', difficulty: 'easy' },
  { id: 'ana_15', text: 'The medial longitudinal arch of the foot is maintained primarily by which structure?', options: ['Plantar calcaneonavicular (spring) ligament', 'Plantar fascia', 'Long plantar ligament', 'Tibialis anterior tendon'], correct: 0, explanation: 'The plantar calcaneonavicular (spring) ligament is the key passive support of the medial longitudinal arch, supporting the head of talus at its apex.', difficulty: 'hard' },

  // --- THORAX ---
  { id: 'ana_16', text: 'The foramen of Morgagni (substernal) is located between which structures of the diaphragm?', options: ['Sternal and costal parts', 'Costal and lumbar parts', 'Left and right crura', 'Around the aortic hiatus'], correct: 0, explanation: 'The foramen of Morgagni is a potential weak area between the sternal and costal parts of the diaphragm. Herniation here is called Morgagni hernia.', difficulty: 'hard' },
  { id: 'ana_17', text: 'The intercostal neurovascular bundle runs in the groove of the rib in the order (from superior to inferior):', options: ['Vein, Artery, Nerve', 'Artery, Vein, Nerve', 'Nerve, Artery, Vein', 'Vein, Nerve, Artery'], correct: 0, explanation: 'The intercostal neurovascular bundle runs in the costal groove in the order: Vein, Artery, Nerve (VAN) from superior to inferior. Injections/needles should be passed above the lower rib to avoid the bundle.', difficulty: 'easy' },
  { id: 'ana_18', text: 'The right lung has how many lobes and fissures?', options: ['2 lobes, 1 fissure', '3 lobes, 2 fissures', '2 lobes, 2 fissures', '3 lobes, 1 fissure'], correct: 1, explanation: 'The right lung has 3 lobes (upper, middle, lower) separated by 2 fissures: the horizontal fissure (separates upper from middle) and the oblique fissure (separates middle from lower).', difficulty: 'easy' },

  // --- ABDOMEN ---
  { id: 'ana_19', text: 'The McBurney\'s point is located:', options: ['At the umbilicus', 'One-third of the way from ASIS to umbilicus', 'Two-thirds of the way from umbilicus to ASIS', 'One-third of the way from umbilicus to ASIS'], correct: 2, explanation: 'McBurney\'s point is located at two-thirds of the way from the umbilicus to the right anterior superior iliac spine (ASIS). Tenderness here is a sign of appendicitis.', difficulty: 'easy' },
  { id: 'ana_20', text: 'The portal vein is formed by the union of:', options: ['Superior mesenteric and hepatic veins', 'Splenic and superior mesenteric veins', 'Inferior mesenteric and splenic veins', 'Hepatic and splenic veins'], correct: 1, explanation: 'The portal vein is formed behind the neck of the pancreas by the union of the splenic vein and the superior mesenteric vein.', difficulty: 'medium' },
  { id: 'ana_21', text: 'A patient presents with referred pain to the right shoulder after a road traffic accident. Which organ is most likely injured?', options: ['Stomach', 'Spleen', 'Right kidney', 'Liver'], correct: 3, explanation: 'Liver injury causes irritation of the diaphragm (supplied by phrenic nerve C3,4,5), referring pain to the right shoulder via C4 dermatome.', difficulty: 'medium' },
  { id: 'ana_22', text: 'The Hesselbach\'s triangle is bounded by:', options: ['Inguinal ligament, rectus abdominis, inferior epigastric vessels', 'Inguinal ligament, sartorius, femoral vein', 'Transversalis fascia, iliac vessels, inguinal ligament', 'External oblique, internal oblique, inguinal ligament'], correct: 0, explanation: 'Hesselbach\'s triangle: medially by rectus abdominis, inferiorly by inguinal ligament, laterally by inferior epigastric vessels. Direct inguinal hernias pass through this triangle.', difficulty: 'hard' },

  // --- HEAD & NECK ---
  { id: 'ana_23', text: 'The parotid gland is pierced by which nerve?', options: ['Trigeminal nerve', 'Glossopharyngeal nerve', 'Facial nerve', 'Hypoglossal nerve'], correct: 2, explanation: 'The facial nerve (CN VII) emerges from the stylomastoid foramen and enters and divides within the parotid gland into its five terminal branches (temporal, zygomatic, buccal, marginal mandibular, cervical).', difficulty: 'easy' },
  { id: 'ana_24', text: 'A patient cannot shrug his shoulder and has difficulty turning his head to the opposite side. Which nerve is damaged?', options: ['C3 spinal nerve', 'Accessory nerve (CN XI)', 'Facial nerve', 'Glossopharyngeal nerve'], correct: 1, explanation: 'The accessory nerve (CN XI) supplies sternocleidomastoid (turns head to opposite side) and trapezius (shrugs shoulder). Damage causes these deficits.', difficulty: 'medium' },

  // --- NEUROANATOMY ---
  { id: 'ana_25', text: 'A lesion of the right optic tract will cause:', options: ['Right monocular blindness', 'Left homonymous hemianopia', 'Right homonymous hemianopia', 'Bitemporal hemianopia'], correct: 1, explanation: 'The right optic tract carries fibers from the right half of each retina (representing the left visual field). Damage causes left homonymous hemianopia.', difficulty: 'hard' },
  { id: 'ana_26', text: 'The blood-brain barrier is mainly formed by:', options: ['Ependymal cells', 'Astrocyte foot processes and tight junctions of endothelial cells', 'Microglia', 'Oligodendrocytes'], correct: 1, explanation: 'The BBB is primarily formed by the tight junctions between cerebral endothelial cells, with a supporting role from astrocyte end-feet which induce these tight junctions.', difficulty: 'medium' },
  { id: 'ana_27', text: 'CSF is produced by:', options: ['Arachnoid granulations', 'Dural sinuses', 'Choroid plexus', 'Ependymal cells of central canal'], correct: 2, explanation: 'CSF is primarily produced (~70%) by the choroid plexus of the lateral, third, and fourth ventricles. It is absorbed mainly at the arachnoid granulations.', difficulty: 'easy' },
  { id: 'ana_28', text: 'A patient has weakness of all muscles on the right side of the body with loss of pain and temperature on the left side. This pattern suggests a lesion in the:', options: ['Left cerebral hemisphere', 'Right cerebral cortex', 'Right half of spinal cord (Brown-Sequard)', 'Left brainstem'], correct: 2, explanation: 'This is Brown-Séquard syndrome. Right-sided motor weakness and loss of proprioception (ipsilateral) + left-sided loss of pain/temperature (contralateral) indicates right hemicord injury.', difficulty: 'hard' },

  // --- EMBRYOLOGY ---
  { id: 'ana_29', text: 'A Meckel\'s diverticulum is a remnant of the:', options: ['Allantois', 'Vitello-intestinal (omphalomesenteric) duct', 'Ductus venosus', 'Umbilical vein'], correct: 1, explanation: 'Meckel\'s diverticulum is a remnant of the vitello-intestinal (omphalomesenteric) duct. It is found in 2% of people, 2 feet from ileocecal valve, 2 inches long.', difficulty: 'medium' },
  { id: 'ana_30', text: 'The neural crest cells do NOT give rise to:', options: ['Melanocytes', 'Schwann cells', 'Oligodendrocytes', 'Adrenal medullary cells'], correct: 2, explanation: 'Oligodendrocytes are derived from the neural tube, NOT neural crest. Neural crest cells give rise to melanocytes, Schwann cells, adrenal medullary cells, peripheral ganglia, and craniofacial cartilage.', difficulty: 'hard' },
];

// ============================================================
// PHYSIOLOGY — Guyton & Hall, Ganong
// ============================================================
const physiologyMCQs = [
  // --- CARDIOVASCULAR ---
  { id: 'phy_1', text: 'The Frank-Starling law of the heart states that:', options: ['Heart rate increases with venous return', 'Stroke volume increases with increased preload', 'Cardiac output decreases during exercise', 'Afterload determines heart rate'], correct: 1, explanation: 'The Frank-Starling law states that within physiological limits, the heart pumps all the blood that returns to it. Increased preload (end-diastolic volume) stretches sarcomeres, increasing force of contraction and stroke volume.', difficulty: 'medium' },
  { id: 'phy_2', text: 'Which portion of the ECG represents ventricular repolarization?', options: ['P wave', 'QRS complex', 'T wave', 'PR interval'], correct: 2, explanation: 'The T wave represents ventricular repolarization. The P wave = atrial depolarization, QRS = ventricular depolarization, PR interval = AV conduction time.', difficulty: 'easy' },
  { id: 'phy_3', text: 'The normal pacemaker of the heart is the:', options: ['AV node', 'Bundle of His', 'SA node', 'Purkinje fibers'], correct: 2, explanation: 'The SA (sinoatrial) node is the normal pacemaker with an intrinsic rate of 60-100 bpm. It has the fastest spontaneous depolarization rate due to the "funny current" (If).', difficulty: 'easy' },
  { id: 'phy_4', text: 'A 70 kg patient has a cardiac output of 5.6 L/min and HR of 70 bpm. What is the stroke volume?', options: ['60 mL', '70 mL', '80 mL', '90 mL'], correct: 2, explanation: 'Stroke Volume = Cardiac Output / Heart Rate = 5600 mL/min ÷ 70 bpm = 80 mL. This is a normal adult stroke volume.', difficulty: 'medium' },
  { id: 'phy_5', text: 'During isovolumetric contraction of the heart:', options: ['Both AV and semilunar valves are open', 'AV valves are open, semilunar valves closed', 'Both valves are closed, pressure rises', 'Semilunar valves are open, AV valves closed'], correct: 2, explanation: 'During isovolumetric contraction, all valves are closed. Ventricular pressure rises rapidly without change in volume. It ends when ventricular pressure exceeds aortic pressure, opening the aortic valve.', difficulty: 'medium' },
  { id: 'phy_6', text: 'The second heart sound (S2) is caused by:', options: ['Closure of AV valves', 'Opening of semilunar valves', 'Closure of semilunar valves', 'Rapid ventricular filling'], correct: 2, explanation: 'S2 is caused by closure of the aortic and pulmonary (semilunar) valves at the end of ventricular systole. A2 precedes P2 (aortic before pulmonary).', difficulty: 'easy' },
  { id: 'phy_7', text: 'Widened pulse pressure (increased difference between systolic and diastolic BP) is seen in:', options: ['Cardiac tamponade', 'Aortic stenosis', 'Aortic regurgitation', 'Hypovolemic shock'], correct: 2, explanation: 'Aortic regurgitation causes high systolic pressure (increased stroke volume) and low diastolic pressure (backflow), resulting in widened pulse pressure. This is the mechanism of Corrigan\'s pulse.', difficulty: 'hard' },
  { id: 'phy_8', text: 'Which baroreceptors are most important in short-term blood pressure regulation?', options: ['Atrial stretch receptors', 'Carotid sinus and aortic arch baroreceptors', 'Renal juxtaglomerular cells', 'Pulmonary stretch receptors'], correct: 1, explanation: 'Carotid sinus and aortic arch baroreceptors are high-pressure baroreceptors that respond rapidly to changes in arterial pressure and are the most important for short-term BP regulation.', difficulty: 'medium' },

  // --- RESPIRATORY ---
  { id: 'phy_9', text: 'The most important stimulus for breathing in normal conditions is:', options: ['Hypoxia (low PaO2)', 'Hypercapnia (high PaCO2)', 'Acidosis (low pH)', 'Low HCO3-'], correct: 1, explanation: 'CO2 (measured as PaCO2) is the most powerful stimulus for normal respiration. CO2 crosses the BBB, lowers CSF pH, and stimulates central chemoreceptors in the medulla. PaO2 is a weaker stimulus.', difficulty: 'medium' },
  { id: 'phy_10', text: 'Tidal volume is approximately:', options: ['150 mL', '350 mL', '500 mL', '1200 mL'], correct: 2, explanation: 'Normal tidal volume (TV) is approximately 500 mL (about 7 mL/kg body weight). Of this, about 150 mL fills the anatomical dead space and 350 mL reaches the alveoli.', difficulty: 'easy' },
  { id: 'phy_11', text: 'Functional Residual Capacity (FRC) equals:', options: ['TV + IRV', 'ERV + RV', 'TLC - VC', 'IC + ERV'], correct: 1, explanation: 'FRC = ERV (Expiratory Reserve Volume) + RV (Residual Volume). It is the lung volume at the end of a normal passive expiration and cannot be measured by simple spirometry.', difficulty: 'medium' },
  { id: 'phy_12', text: 'In asthma, which spirometric pattern is expected?', options: ['Reduced FVC with normal FEV1/FVC ratio', 'Reduced FEV1 with reduced FEV1/FVC ratio', 'Increased TLC with normal FVC', 'Reduced RV with normal FVC'], correct: 1, explanation: 'Asthma shows an obstructive pattern: reduced FEV1, with FEV1/FVC ratio < 70%. This improves with bronchodilators (reversibility distinguishes asthma from COPD).', difficulty: 'hard' },
  { id: 'phy_13', text: 'Surfactant is produced by:', options: ['Type I pneumocytes', 'Type II pneumocytes', 'Clara cells', 'Alveolar macrophages'], correct: 1, explanation: 'Pulmonary surfactant (dipalmitoylphosphatidylcholine, DPPC) is produced by Type II pneumocytes. It reduces surface tension, preventing alveolar collapse. Deficiency causes neonatal respiratory distress syndrome.', difficulty: 'easy' },
  { id: 'phy_14', text: 'Oxygen is primarily carried in blood as:', options: ['Dissolved O2 in plasma', 'Oxyhemoglobin (HbO2)', 'Carbaminohemoglobin', 'Bicarbonate'], correct: 1, explanation: 'About 98% of oxygen is carried bound to hemoglobin as oxyhemoglobin. Only about 1.5% is dissolved in plasma. The heme group can carry 4 O2 molecules.', difficulty: 'easy' },

  // --- RENAL ---
  { id: 'phy_15', text: 'The main driving force for glomerular filtration is:', options: ['Oncotic pressure of plasma proteins', 'Hydrostatic pressure in Bowman\'s capsule', 'Glomerular hydrostatic pressure', 'Tubular osmotic pressure'], correct: 2, explanation: 'Glomerular filtration occurs because hydrostatic pressure in glomerular capillaries (~60 mmHg) exceeds the sum of oncotic pressure (~32 mmHg) and Bowman\'s capsule pressure (~18 mmHg). Net filtration pressure ≈ 10 mmHg.', difficulty: 'medium' },
  { id: 'phy_16', text: 'Aldosterone acts primarily on which part of the nephron?', options: ['Proximal convoluted tubule', 'Loop of Henle (descending)', 'Distal convoluted tubule and collecting duct', 'Glomerulus'], correct: 2, explanation: 'Aldosterone acts on the principal cells of the distal convoluted tubule and collecting duct to increase Na+ reabsorption (via increased ENaC channels) and K+ secretion.', difficulty: 'easy' },
  { id: 'phy_17', text: 'ADH (Vasopressin) increases water reabsorption by inserting which channels into the collecting duct?', options: ['ENaC channels', 'NKCC2 cotransporters', 'Aquaporin-2 (AQP2)', 'V1 receptors'], correct: 2, explanation: 'ADH binds V2 receptors on collecting duct cells, activating cAMP cascade which causes insertion of aquaporin-2 (AQP2) water channels into the apical membrane, increasing water permeability.', difficulty: 'medium' },
  { id: 'phy_18', text: 'Normal GFR in a healthy adult is approximately:', options: ['60 mL/min', '90 mL/min', '125 mL/min', '180 mL/min'], correct: 2, explanation: 'Normal GFR is approximately 125 mL/min (180 L/day). Of this, 99% is reabsorbed, producing about 1.5 L of urine per day. GFR is used clinically to estimate renal function.', difficulty: 'easy' },

  // --- GASTROINTESTINAL ---
  { id: 'phy_19', text: 'Which cells of the stomach secrete intrinsic factor?', options: ['Chief cells', 'G cells', 'Parietal (oxyntic) cells', 'Mucous neck cells'], correct: 2, explanation: 'Parietal (oxyntic) cells of the gastric fundus and body secrete both intrinsic factor (essential for B12 absorption in terminal ileum) and HCl. Autoimmune destruction causes pernicious anemia.', difficulty: 'medium' },
  { id: 'phy_20', text: 'The migrating motor complex (MMC) is often called the "housekeeper" of the gut. It is initiated by:', options: ['Secretin', 'CCK', 'Motilin', 'VIP'], correct: 2, explanation: 'Motilin (from Mo cells of duodenum) initiates the migrating motor complex (MMC) during the interdigestive period (fasting), sweeping undigested material toward the colon every ~90 minutes.', difficulty: 'hard' },

  // --- ENDOCRINE ---
  { id: 'phy_21', text: 'Insulin facilitates glucose uptake primarily via which glucose transporter?', options: ['GLUT1', 'GLUT2', 'GLUT4', 'GLUT5'], correct: 2, explanation: 'GLUT4 is the insulin-sensitive glucose transporter found in muscle, adipose tissue, and heart. Insulin causes its translocation from intracellular vesicles to the plasma membrane.', difficulty: 'medium' },
  { id: 'phy_22', text: 'A patient has high serum calcium, low phosphate, and high PTH. Where is the lesion?', options: ['Vitamin D deficiency', 'Primary hyperparathyroidism', 'Hypoparathyroidism', 'Secondary hyperparathyroidism'], correct: 1, explanation: 'Primary hyperparathyroidism (usually a parathyroid adenoma) causes: ↑Ca2+, ↓PO4, ↑PTH. PTH increases bone resorption, renal Ca reabsorption, and indirectly increases gut Ca absorption via Vitamin D.', difficulty: 'hard' },
  { id: 'phy_23', text: 'Cortisol has all of the following effects EXCEPT:', options: ['Increases blood glucose', 'Anti-inflammatory action', 'Increases protein synthesis', 'Increases lipolysis'], correct: 2, explanation: 'Cortisol is catabolic — it DECREASES (not increases) protein synthesis in most tissues (except liver) and increases protein catabolism. Other effects include hyperglycemia, anti-inflammatory, and lipolysis.', difficulty: 'hard' },

  // --- NERVE & MUSCLE ---
  { id: 'phy_24', text: 'The resting membrane potential of a neuron is approximately:', options: ['-35 mV', '-70 mV', '+40 mV', '-90 mV'], correct: 1, explanation: 'The resting membrane potential of most neurons is approximately -70 mV. This is maintained primarily by the Na+/K+ ATPase pump and the K+ leak channels.', difficulty: 'easy' },
  { id: 'phy_25', text: 'The neuromuscular junction transmitter is:', options: ['Norepinephrine', 'Dopamine', 'Acetylcholine', 'GABA'], correct: 2, explanation: 'Acetylcholine (ACh) is the neurotransmitter at the neuromuscular junction (NMJ). It binds nicotinic ACh receptors (nAChR) on the motor end plate, causing depolarization and muscle contraction.', difficulty: 'easy' },
  { id: 'phy_26', text: 'During muscle contraction, the length of the H-zone changes because:', options: ['Actin filaments shorten', 'Myosin filaments shorten', 'Actin slides over myosin, reducing the zone without thin filaments', 'Z lines move apart'], correct: 2, explanation: 'H-zone is the central region of the A-band containing only myosin filaments (no actin overlap). During contraction, actin slides inward, reducing and eventually eliminating the H-zone. Z-lines come closer.', difficulty: 'hard' },

  // --- BLOOD ---
  { id: 'phy_27', text: 'The O2-Hb dissociation curve shifts to the RIGHT (Bohr effect) due to:', options: ['Decreased CO2, decreased temperature, increased pH', 'Increased CO2, increased temperature, decreased pH, increased 2,3-DPG', 'Decreased 2,3-DPG, fetal hemoglobin', 'Increased pH, decreased temperature'], correct: 1, explanation: 'Right shift (decreased O2 affinity of Hb, releasing more O2 to tissues) occurs due to increased CO2, H+ (decreased pH), temperature, and 2,3-DPG. Mnemonic: "Right = Tired tissue needs oxygen."', difficulty: 'medium' },
  { id: 'phy_28', text: 'Which coagulation pathway is activated when blood comes into contact with a foreign surface?', options: ['Extrinsic pathway', 'Intrinsic (contact) pathway', 'Common pathway', 'Fibrinolytic pathway'], correct: 1, explanation: 'The intrinsic (contact) pathway is activated when blood contacts collagen or a foreign surface, activating Factor XII (Hageman factor). The extrinsic pathway is activated by tissue factor (thromboplastin).', difficulty: 'medium' },
];

// ============================================================
// BIOCHEMISTRY — Lippincott, Harper, Lehninger
// ============================================================
const biochemistryMCQs = [
  // --- CARBOHYDRATES ---
  { id: 'bc_1', text: 'Glycolysis occurs in the:', options: ['Mitochondrial matrix', 'Inner mitochondrial membrane', 'Cytoplasm (cytosol)', 'Nucleus'], correct: 2, explanation: 'Glycolysis is a cytoplasmic (cytosolic) process. It converts glucose to 2 pyruvate molecules, yielding net 2 ATP and 2 NADH.', difficulty: 'easy' },
  { id: 'bc_2', text: 'The net ATP produced per molecule of glucose in complete aerobic oxidation is approximately:', options: ['2 ATP', '8 ATP', '30-32 ATP', '38 ATP'], correct: 2, explanation: 'Aerobic oxidation of glucose produces approximately 30-32 ATP (modern estimates), accounting for 2 from glycolysis, 2 from TCA cycle substrate-level phosphorylation, and ~26-28 from oxidative phosphorylation.', difficulty: 'easy' },
  { id: 'bc_3', text: 'Pyruvate kinase deficiency causes which condition?', options: ['Gout', 'Hemolytic anemia', 'Galactosemia', 'Phenylketonuria'], correct: 1, explanation: 'Pyruvate kinase (PK) deficiency is the most common glycolytic enzyme deficiency. RBCs depend entirely on glycolysis for ATP; PK deficiency → reduced ATP → hemolytic anemia.', difficulty: 'medium' },
  { id: 'bc_4', text: 'Which enzyme converts glucose-6-phosphate to glucose-1-phosphate?', options: ['Hexokinase', 'Phosphoglucomutase', 'Glucose-6-phosphatase', 'Phosphofructokinase-1'], correct: 1, explanation: 'Phosphoglucomutase converts glucose-6-phosphate ↔ glucose-1-phosphate. This is essential in glycogen synthesis (G1P → UDP-glucose → glycogen) and glycogenolysis.', difficulty: 'medium' },
  { id: 'bc_5', text: 'The rate-limiting (key regulatory) enzyme of glycolysis is:', options: ['Hexokinase', 'Aldolase', 'Phosphofructokinase-1 (PFK-1)', 'Pyruvate kinase'], correct: 2, explanation: 'PFK-1 is the rate-limiting enzyme of glycolysis. It is stimulated by AMP, ADP, fructose-2,6-bisphosphate, and inhibited by ATP, citrate, H+ (acidosis).', difficulty: 'medium' },
  { id: 'bc_6', text: 'Von Gierke\'s disease (Type I glycogen storage disease) is due to deficiency of:', options: ['Liver phosphorylase', 'Branching enzyme', 'Glucose-6-phosphatase', 'Lysosomal alpha-glucosidase'], correct: 2, explanation: 'Von Gierke\'s disease is caused by glucose-6-phosphatase deficiency (liver/kidney). Leads to massive hepatomegaly, severe fasting hypoglycemia, lactic acidosis, hyperuricemia, and hyperlipidemia.', difficulty: 'hard' },

  // --- LIPIDS ---
  { id: 'bc_7', text: 'The enzyme responsible for the rate-limiting step of fatty acid synthesis is:', options: ['Fatty acid synthase (FAS)', 'Acetyl-CoA carboxylase (ACC)', 'Malonyl-CoA transacylase', 'Citrate lyase'], correct: 1, explanation: 'Acetyl-CoA carboxylase (ACC) catalyzes the conversion of acetyl-CoA to malonyl-CoA (the committed step). It is activated by insulin/citrate and inhibited by glucagon, palmitoyl-CoA, and AMPK.', difficulty: 'medium' },
  { id: 'bc_8', text: 'Beta-oxidation of fatty acids occurs in the:', options: ['Cytoplasm', 'Endoplasmic reticulum', 'Mitochondrial matrix', 'Peroxisomes only'], correct: 2, explanation: 'Beta-oxidation predominantly occurs in the mitochondrial matrix. Long-chain fatty acids require carnitine shuttle to cross the inner mitochondrial membrane. Very long-chain fatty acids are oxidized in peroxisomes.', difficulty: 'easy' },
  { id: 'bc_9', text: 'A patient presents with fasting hypoglycemia, non-ketotic hypoglycemia, and elevated long-chain acylcarnitines. What is the most likely diagnosis?', options: ['MCAD deficiency', 'Carnitine palmitoyl transferase I (CPT-I) deficiency', 'SCAD deficiency', 'Propionic acidemia'], correct: 1, explanation: 'CPT-I deficiency prevents long-chain fatty acid transport into mitochondria. This causes: fasting hypoglycemia (can\'t do beta-oxidation), hypoketosis (no acetyl-CoA for ketogenesis), and elevated acylcarnitines.', difficulty: 'hard' },
  { id: 'bc_10', text: 'Ketone bodies are produced in:', options: ['Liver mitochondria only', 'Peripheral muscle mitochondria', 'Brain astrocytes', 'Adipose tissue'], correct: 0, explanation: 'Ketone bodies (acetoacetate, beta-hydroxybutyrate, acetone) are produced exclusively in liver mitochondria from acetyl-CoA (during prolonged fasting or uncontrolled diabetes). They are used by extrahepatic tissues.', difficulty: 'medium' },

  // --- PROTEINS & AMINO ACIDS ---
  { id: 'bc_11', text: 'The urea cycle primarily occurs in the:', options: ['Liver', 'Kidney', 'Intestine', 'Muscle'], correct: 0, explanation: 'The urea cycle occurs primarily in hepatocytes (liver). Urea is then transported in blood to the kidney for excretion. Liver failure leads to hyperammonemia.', difficulty: 'easy' },
  { id: 'bc_12', text: 'Phenylketonuria (PKU) is caused by deficiency of:', options: ['Tyrosinase', 'Phenylalanine hydroxylase', 'Homogentisate oxidase', 'Fumarylacetoacetase'], correct: 1, explanation: 'PKU is caused by deficiency of phenylalanine hydroxylase (or its cofactor BH4), leading to accumulation of phenylalanine and its toxic metabolites. Causes intellectual disability if untreated.', difficulty: 'medium' },
  { id: 'bc_13', text: 'Which amino acid is the precursor for both catecholamines and melanin?', options: ['Tryptophan', 'Phenylalanine', 'Tyrosine', 'Histidine'], correct: 2, explanation: 'Tyrosine is the precursor for catecholamines (dopamine, norepinephrine, epinephrine) via DOPA and for melanin via DOPA → dopaquinone. Tyrosine is also used to make thyroid hormones.', difficulty: 'medium' },
  { id: 'bc_14', text: 'In negative nitrogen balance, the body is:', options: ['Retaining more nitrogen than it loses', 'Losing more nitrogen than it takes in (net catabolism)', 'Maintaining equal nitrogen intake and output', 'Building new proteins at a high rate'], correct: 1, explanation: 'Negative nitrogen balance occurs when nitrogen excretion exceeds intake — seen in starvation, burns, severe illness, or prolonged corticosteroid use (net protein catabolism).', difficulty: 'medium' },

  // --- NUCLEOTIDES & DNA ---
  { id: 'bc_15', text: 'Allopurinol treats gout by inhibiting which enzyme?', options: ['Adenosine deaminase', 'Xanthine oxidase', 'HGPRT', 'Phosphoribosylpyrophosphate (PRPP) synthetase'], correct: 1, explanation: 'Allopurinol is a xanthine oxidase inhibitor. Xanthine oxidase converts hypoxanthine → xanthine → uric acid. Inhibition reduces uric acid production, treating gout and urate nephropathy.', difficulty: 'medium' },
  { id: 'bc_16', text: 'Which statement about DNA replication is correct?', options: ['It is conservative (daughter DNAs contain both original strands)', 'It proceeds in a 3\'→5\' direction', 'It is semi-conservative (each daughter DNA has one original strand)', 'RNA polymerase performs the main replication'], correct: 2, explanation: 'DNA replication is semi-conservative (Meselson-Stahl experiment). Each daughter DNA molecule has one original (template) strand and one newly synthesized strand. Synthesis is 5\'→3\'.', difficulty: 'easy' },
  { id: 'bc_17', text: 'Which enzyme repairs the nicks in DNA after Okazaki fragment processing?', options: ['DNA polymerase I', 'DNA ligase', 'Helicase', 'Primase'], correct: 1, explanation: 'DNA ligase joins Okazaki fragments by forming phosphodiester bonds to seal the nicks in the sugar-phosphate backbone after DNA Pol I has replaced the RNA primers.', difficulty: 'medium' },

  // --- VITAMINS & ENZYMES ---
  { id: 'bc_18', text: 'Vitamin B1 (Thiamine) deficiency causes all of the following EXCEPT:', options: ['Wernicke\'s encephalopathy', 'Beriberi', 'Pellagra', 'Wernicke-Korsakoff syndrome'], correct: 2, explanation: 'Pellagra is caused by Niacin (Vitamin B3) deficiency. Thiamine (B1) deficiency causes Beriberi (wet: cardiac, dry: neurological), and Wernicke\'s encephalopathy/Wernicke-Korsakoff syndrome.', difficulty: 'medium' },
  { id: 'bc_19', text: 'The enzyme that catalyzes the conversion of 5-FIGLU to 5-methyl THF, requiring B12, is involved in:', options: ['Methionine synthase reaction', 'Thymidylate synthase reaction', 'N5,N10-Methylene THF reaction', 'Dihydrofolate reductase reaction'], correct: 0, explanation: 'Methionine synthase uses methylcobalamin (B12) to transfer methyl group from 5-methyl-THF to homocysteine, forming methionine and regenerating THF. B12 deficiency → "methyl-trap" → folate deficiency.', difficulty: 'hard' },
  { id: 'bc_20', text: 'Competitive inhibition is characterized by:', options: ['Decreased Vmax with unchanged Km', 'Unchanged Vmax with increased Km', 'Decreased Vmax with decreased Km', 'Unchanged Vmax and Km'], correct: 1, explanation: 'Competitive inhibitors compete with substrate for the active site, increasing apparent Km (decreased affinity). Vmax is unchanged because the inhibitor can be overcome by increasing substrate concentration.', difficulty: 'medium' },
];

// ============================================================
// PATHOLOGY — Robbins & Cotran
// ============================================================
const pathologyMCQs = [
  // --- CELL INJURY & DEATH ---
  { id: 'pat_1', text: 'The earliest ultrastructural change in reversible cell injury is:', options: ['Nuclear condensation (pyknosis)', 'Mitochondrial condensation and swelling', 'Cell membrane disruption', 'Formation of myelin figures'], correct: 1, explanation: 'The earliest changes in reversible cell injury are mitochondrial changes (condensation, then swelling) and plasma membrane blebbing. These are all ultrastructural (EM level) changes.', difficulty: 'hard' },
  { id: 'pat_2', text: 'Coagulative necrosis is the hallmark of infarcts in which organ(s)?', options: ['Brain', 'Kidney', 'Liver', 'Spleen'], correct: 1, explanation: 'Coagulative necrosis occurs in most solid organs after ischemic infarction (heart, kidney, spleen). The exception is the brain, which undergoes liquefactive necrosis due to high lipid content and proteolytic enzymes.', difficulty: 'medium' },
  { id: 'pat_3', text: 'Ghon complex in pulmonary tuberculosis consists of:', options: ['Apical cavity + pleural effusion', 'Primary focus in lower zone + lymph node calcification', 'Primary subpleural focus + hilar lymph node + connecting lymphatics', 'Bilateral apical infiltrates'], correct: 2, explanation: 'The Ghon complex = Ghon focus (primary subpleural parenchymal lesion, often in lower zones) + draining lymphatics + hilar lymph node enlargement. It calcifies over time.', difficulty: 'medium' },
  { id: 'pat_4', text: 'Caseating granulomas are most characteristically seen in:', options: ['Sarcoidosis', 'Crohn\'s disease', 'Tuberculosis', 'Berylliosis'], correct: 2, explanation: 'Caseating granulomas (cheese-like central necrosis) are the hallmark of tuberculosis. Sarcoidosis, berylliosis, and Crohn\'s disease show NON-caseating (hard) granulomas.', difficulty: 'easy' },
  { id: 'pat_5', text: 'Which type of necrosis is characteristically seen in wet gangrene?', options: ['Coagulative necrosis', 'Liquefactive necrosis', 'Fat necrosis', 'Caseous necrosis'], correct: 1, explanation: 'Wet gangrene involves liquefactive necrosis due to secondary bacterial infection superimposed on ischemic (coagulative) necrosis. The liquefactive component comes from the enzyme-rich bacterial and leukocytic exudate.', difficulty: 'medium' },

  // --- INFLAMMATION ---
  { id: 'pat_6', text: 'The most potent chemotactic agent for neutrophils is:', options: ['Histamine', 'C5a (complement fragment)', 'Prostaglandin E2', 'IL-4'], correct: 1, explanation: 'C5a is a potent chemotactic agent for neutrophils. Other chemotactic agents include leukotriene B4 (LTB4), IL-8, and bacterial peptides (fMet-Leu-Phe). C5a also activates mast cells.', difficulty: 'medium' },
  { id: 'pat_7', text: 'Which cells predominate in chronic inflammation?', options: ['Neutrophils and eosinophils', 'Macrophages, lymphocytes, and plasma cells', 'Basophils and mast cells', 'Platelets and monocytes'], correct: 1, explanation: 'Chronic inflammation is characterized by macrophages (key player), lymphocytes (T and B cells), and plasma cells. Macrophages are the primary effector cells, producing cytokines that perpetuate inflammation.', difficulty: 'easy' },
  { id: 'pat_8', text: 'IL-1, IL-6, and TNF-alpha cause which systemic effect responsible for fever?', options: ['Direct action on hypothalamic thermostat', 'Induce PGE2 synthesis in the hypothalamus via COX-2', 'Stimulate sweat gland suppression', 'Cause vasoconstriction in skin'], correct: 1, explanation: 'Endogenous pyrogens (IL-1, IL-6, TNF-α) stimulate COX-2 in hypothalamic endothelial cells, producing PGE2. PGE2 raises the hypothalamic set-point, causing fever. NSAIDs/aspirin inhibit COX-2, reducing PGE2.', difficulty: 'hard' },

  // --- NEOPLASIA ---
  { id: 'pat_9', text: 'The hallmark of malignancy distinguishing it from benign tumors is:', options: ['Rapid growth rate', 'Large tumor size', 'Invasion and metastasis', 'Pleomorphism'], correct: 2, explanation: 'The definitive hallmark of malignancy is invasion (into surrounding tissue) and metastasis (spread to distant sites). Benign tumors grow expansively but do not invade or metastasize.', difficulty: 'easy' },
  { id: 'pat_10', text: 'The most common route of metastasis of carcinomas is:', options: ['Hematogenous', 'Lymphatic', 'Transcoelomic', 'Perineural'], correct: 1, explanation: 'Lymphatic metastasis is the most common initial route for carcinomas (epithelial cancers). This is why sentinel lymph node biopsy is important in breast cancer. Sarcomas prefer hematogenous spread.', difficulty: 'medium' },
  { id: 'pat_11', text: 'p53 tumor suppressor gene is called the "guardian of the genome" because it:', options: ['Promotes cell proliferation', 'Arrests cell cycle at G1/S checkpoint if DNA is damaged', 'Stimulates angiogenesis', 'Promotes mutation accumulation'], correct: 1, explanation: 'p53 detects DNA damage and either arrests the cell cycle at G1/S checkpoint (to allow repair) or triggers apoptosis if damage is irreparable. Mutation of TP53 is the most common genetic change in human cancers.', difficulty: 'medium' },
  { id: 'pat_12', text: 'A Virchow\'s node (Troisier\'s sign) enlargement is associated with carcinoma of the:', options: ['Breast', 'Lung', 'Stomach', 'Thyroid'], correct: 2, explanation: 'Virchow\'s node (left supraclavicular node) enlargement by Troisier\'s sign is classic for gastric carcinoma metastasis via the thoracic duct. It can also occur with other abdominal/pelvic malignancies.', difficulty: 'medium' },
  { id: 'pat_13', text: 'Reed-Sternberg cells are pathognomonic of:', options: ['Non-Hodgkin lymphoma', 'Hodgkin lymphoma', 'Burkitt lymphoma', 'CML'], correct: 1, explanation: 'Reed-Sternberg cells (large binucleate cells with prominent "owl-eye" nucleoli) are pathognomonic of Hodgkin lymphoma. They are CD15+, CD30+ and derived from germinal center B cells.', difficulty: 'easy' },

  // --- CARDIOVASCULAR PATHOLOGY ---
  { id: 'pat_14', text: 'The most common cause of death in acute MI is:', options: ['Cardiac rupture', 'Ventricular aneurysm', 'Cardiogenic shock', 'Ventricular fibrillation (arrhythmia)'], correct: 3, explanation: 'Ventricular fibrillation is the most common cause of sudden death in the first hour of acute MI. This is why early defibrillation and ACLS are critical. Later complications include cardiac rupture, cardiogenic shock.', difficulty: 'hard' },
  { id: 'pat_15', text: 'The type of atherosclerotic plaque most prone to rupture and thrombus formation is:', options: ['Calcified stable plaque', 'Large stable plaque with thick fibrous cap', 'Vulnerable plaque with thin fibrous cap and large lipid core', 'Organized thrombus'], correct: 2, explanation: 'Vulnerable plaques have a large necrotic lipid core, thin fibrous cap, and abundant inflammatory cells (macrophages/foam cells). Rupture exposes the thrombogenic core, causing acute coronary syndrome.', difficulty: 'hard' },
];

// ============================================================
// PHARMACOLOGY — Katzung, Lippincott
// ============================================================
const pharmacologyMCQs = [
  // --- PHARMACOKINETICS ---
  { id: 'pha_1', text: 'The half-life of a drug is the time required to:', options: ['Eliminate 100% of the drug', 'Reduce drug concentration by 50%', 'Achieve peak plasma concentration', 'Reach steady-state concentration'], correct: 1, explanation: 'Half-life (t½) is the time for drug concentration to decrease by 50%. It determines dosing interval and time to steady state (4-5 half-lives). t½ = 0.693 × Vd / CL.', difficulty: 'easy' },
  { id: 'pha_2', text: 'First-pass metabolism is most relevant for drugs given by which route?', options: ['IV injection', 'Sublingual', 'Oral route', 'Transdermal'], correct: 2, explanation: 'First-pass metabolism occurs when orally absorbed drugs pass through the portal circulation and are metabolized by the liver before reaching systemic circulation, greatly reducing bioavailability.', difficulty: 'easy' },
  { id: 'pha_3', text: 'A drug with a narrow therapeutic index requires careful monitoring because:', options: ['It has a very long half-life', 'The toxic dose is close to the therapeutic dose', 'It is rapidly eliminated', 'It has high protein binding'], correct: 1, explanation: 'Narrow therapeutic index (e.g., digoxin, warfarin, lithium, phenytoin) means the difference between effective dose and toxic dose is small, requiring close monitoring of drug levels.', difficulty: 'medium' },
  { id: 'pha_4', text: 'Phase II drug metabolism primarily involves:', options: ['Oxidation by CYP450 enzymes', 'Conjugation reactions (glucuronidation, sulfation, acetylation)', 'Hydrolysis of ester bonds', 'Reduction reactions'], correct: 1, explanation: 'Phase II reactions are synthetic (conjugation) reactions: glucuronidation, sulfation, acetylation, methylation, and glutathione conjugation. They generally increase water solubility for renal excretion.', difficulty: 'medium' },

  // --- AUTONOMIC ---
  { id: 'pha_5', text: 'Atropine blocks which type of receptor?', options: ['Nicotinic acetylcholine receptors', 'Muscarinic acetylcholine receptors', 'Alpha-adrenergic receptors', 'Beta-adrenergic receptors'], correct: 1, explanation: 'Atropine is a competitive muscarinic receptor antagonist. It blocks M1-M5 receptors causing: dry mouth, mydriasis, tachycardia, urinary retention, decreased GI motility, dry skin.', difficulty: 'easy' },
  { id: 'pha_6', text: 'Propranolol is a non-selective beta-blocker. Which side effect is most dangerous in asthmatics?', options: ['Bradycardia', 'Hypoglycemia masking', 'Bronchoconstriction via β2 blockade', 'Fatigue'], correct: 2, explanation: 'Non-selective beta-blockers block β2 receptors in bronchial smooth muscle, causing bronchoconstriction. This is dangerous in asthmatics. Cardioselective beta-blockers (metoprolol, atenolol) are safer.', difficulty: 'medium' },
  { id: 'pha_7', text: 'Phenylephrine is used as a nasal decongestant because it:', options: ['Blocks α1-adrenergic receptors', 'Stimulates β2 receptors', 'Stimulates α1-adrenergic receptors causing vasoconstriction', 'Inhibits histamine release'], correct: 2, explanation: 'Phenylephrine is a selective α1 agonist that causes vasoconstriction of nasal mucosal blood vessels, reducing congestion and edema. Unlike pseudoephedrine, it doesn\'t have CNS stimulant effects.', difficulty: 'medium' },

  // --- CARDIOVASCULAR ---
  { id: 'pha_8', text: 'The mechanism of action of ACE inhibitors (e.g., Enalapril) is:', options: ['Block angiotensin II AT1 receptors', 'Inhibit conversion of Angiotensin I to Angiotensin II by ACE', 'Block aldosterone receptors', 'Inhibit renin release'], correct: 1, explanation: 'ACE inhibitors block angiotensin-converting enzyme (ACE/kininase II), preventing conversion of Ang I → Ang II, and also preventing bradykinin breakdown. Result: vasodilation, reduced aldosterone, reduced preload/afterload.', difficulty: 'easy' },
  { id: 'pha_9', text: 'A patient on heparin develops HIT (Heparin-Induced Thrombocytopenia). The safest alternative anticoagulant is:', options: ['Warfarin (immediately)', 'Low molecular weight heparin', 'Argatroban (direct thrombin inhibitor)', 'Aspirin'], correct: 2, explanation: 'In HIT, heparin must be stopped immediately. Warfarin is contraindicated initially (risk of limb gangrene). Argatroban or bivalirudin (direct thrombin inhibitors) are safe alternatives as they don\'t cross-react with HIT antibodies.', difficulty: 'hard' },
  { id: 'pha_10', text: 'Digoxin toxicity causes which characteristic arrhythmia?', options: ['AV block with junctional escape rhythm', 'Supraventricular tachycardia', 'Broad complex QRS without arrhythmia', 'Sinus tachycardia'], correct: 0, explanation: 'Digoxin toxicity characteristically causes PAT with block (paroxysmal atrial tachycardia with AV block) — the combination of increased automaticity (AV junctional escape) and AV block is pathognomonic.', difficulty: 'hard' },

  // --- ANTIMICROBIALS ---
  { id: 'pha_11', text: 'Beta-lactam antibiotics kill bacteria by:', options: ['Inhibiting 50S ribosomal subunit', 'Disrupting cell membrane integrity', 'Inhibiting transpeptidation (cross-linking) of peptidoglycan cell wall', 'Inhibiting DNA gyrase'], correct: 2, explanation: 'Beta-lactams (penicillins, cephalosporins, carbapenems) inhibit transpeptidases (Penicillin-Binding Proteins, PBPs), preventing cross-linking of peptidoglycan. This weakens the cell wall, causing osmotic lysis.', difficulty: 'medium' },
  { id: 'pha_12', text: 'Aminoglycosides (e.g., Gentamicin) cause nephrotoxicity because they:', options: ['Are freely filtered but not reabsorbed', 'Accumulate in proximal tubular cells and cause direct cytotoxicity', 'Cause intense renal vasoconstriction', 'Block renal ADH receptors'], correct: 1, explanation: 'Aminoglycosides are concentrated in proximal tubular cells (via cation transport), causing mitochondrial damage and cell death (acute tubular necrosis). Risk increases with duration of therapy and concurrent nephrotoxins.', difficulty: 'hard' },
  { id: 'pha_13', text: 'A patient develops tendon rupture after taking an antibiotic for UTI. Which drug is responsible?', options: ['Amoxicillin', 'Trimethoprim-sulfamethoxazole', 'Fluoroquinolone (e.g., Ciprofloxacin)', 'Nitrofurantoin'], correct: 2, explanation: 'Fluoroquinolones (ciprofloxacin, levofloxacin) are associated with tendinopathy and tendon rupture (especially Achilles tendon), arthropathy, peripheral neuropathy, and QT prolongation. Contraindicated in children/pregnancy.', difficulty: 'medium' },

  // --- CNS DRUGS ---
  { id: 'pha_14', text: 'The mechanism of action of benzodiazepines is:', options: ['Block NMDA glutamate receptors', 'Potentiate GABA-A receptor by increasing frequency of Cl- channel opening', 'Block serotonin reuptake', 'Inhibit MAO enzymes'], correct: 1, explanation: 'Benzodiazepines bind to the GABA-A receptor at a site distinct from GABA, increasing the frequency of Cl- channel opening when GABA is present. This enhances inhibitory neurotransmission (anxiolytic, sedative, anticonvulsant).', difficulty: 'medium' },
  { id: 'pha_15', text: 'Serotonin syndrome is caused by excess serotonergic activity and can occur with:', options: ['SSRI + MAOI combination', 'SSRI + beta-blocker', 'Tricyclic + aspirin', 'Lithium + haloperidol'], correct: 0, explanation: 'Serotonin syndrome occurs with combinations increasing serotonin: SSRI+MAOI, SSRI+tramadol, SSRI+linezolid. Features: hyperthermia, agitation, clonus, tremor, mydriasis. It\'s a medical emergency.', difficulty: 'hard' },
];

// ============================================================
// MEDICINE — Davidson, Kumar & Clark
// ============================================================
const medicineMCQs = [
  { id: 'med_1', text: 'The most sensitive initial test for suspected myocardial infarction is:', options: ['ECG (ST elevation)', 'CK-MB', 'Troponin I or T', 'Myoglobin'], correct: 2, explanation: 'Troponin I and T are the most sensitive and specific biomarkers for myocardial injury. They rise within 4-6 hours and remain elevated for 10-14 days, useful for late diagnosis.', difficulty: 'medium' },
  { id: 'med_2', text: 'A patient has BP 160/100 on 3 occasions. Investigations show: K+ 2.8, HCO3- 28, normal aldosterone:renin ratio. Most likely diagnosis:', options: ['Primary hyperaldosteronism (Conn\'s syndrome)', 'Cushing\'s syndrome', 'Renovascular hypertension', 'Essential hypertension with diuretic use'], correct: 0, explanation: 'Conn\'s syndrome (primary hyperaldosteronism): hypertension + hypokalemia + metabolic alkalosis with elevated aldosterone and suppressed renin (low aldosterone:renin ratio actually means high ratio). Most common cause: adrenal adenoma.', difficulty: 'hard' },
  { id: 'med_3', text: 'A 55-year-old smoker presents with progressive dyspnea, barrel chest, and decreased breath sounds. FEV1/FVC = 58%. Most likely diagnosis:', options: ['Asthma', 'Pulmonary fibrosis', 'COPD (Emphysema)', 'Pulmonary embolism'], correct: 2, explanation: 'COPD: history of smoking + progressive dyspnea + barrel chest (hyperinflation) + obstructive spirometry (FEV1/FVC < 70%). Emphysema causes decreased breath sounds due to air trapping and hyperinflated lungs.', difficulty: 'medium' },
  { id: 'med_4', text: 'The CURB-65 score for community-acquired pneumonia severity includes all of the following EXCEPT:', options: ['Confusion', 'Urea > 7 mmol/L', 'Respiratory rate ≥ 30/min', 'Oxygen saturation < 90%'], correct: 3, explanation: 'CURB-65: Confusion, Urea > 7 mmol/L, RR ≥ 30/min, Blood pressure < 90 systolic or ≤ 60 diastolic, Age ≥ 65. O2 saturation is NOT part of CURB-65 (it is in PSI/PORT score).', difficulty: 'hard' },
  { id: 'med_5', text: 'Which of the following is the FIRST-LINE treatment for Helicobacter pylori eradication?', options: ['Omeprazole alone', 'Triple therapy: PPI + Clarithromycin + Amoxicillin for 7-14 days', 'Metronidazole alone', 'H2-blocker + Bismuth'], correct: 1, explanation: 'Standard triple therapy (PPI + clarithromycin + amoxicillin or metronidazole) for 7-14 days is first-line for H. pylori eradication. "Test and treat" is the preferred strategy before endoscopy in young patients.', difficulty: 'medium' },
  { id: 'med_6', text: 'Type 1 Diabetes Mellitus differs from Type 2 primarily in that:', options: ['Type 1 is more common in obese adults', 'Type 1 is managed with diet alone initially', 'Type 1 has absolute insulin deficiency due to autoimmune beta-cell destruction', 'Type 2 always requires insulin from onset'], correct: 2, explanation: 'T1DM: autoimmune destruction of pancreatic beta cells → absolute insulin deficiency → ketoacidosis-prone. T2DM: insulin resistance + relative insulin deficiency; managed initially with lifestyle and oral agents.', difficulty: 'easy' },
  { id: 'med_7', text: 'A patient presents with jaundice, dark urine, pale stools, and pruritus. Bilirubin is predominantly conjugated. This pattern suggests:', options: ['Hemolytic jaundice', 'Gilbert\'s syndrome', 'Obstructive (cholestatic) jaundice', 'Hepatocellular jaundice'], correct: 2, explanation: 'Obstructive/cholestatic jaundice: predominantly conjugated (direct) hyperbilirubinemia + dark urine (bilirubinuria) + pale stools (absent urobilinogen) + pruritus (bile salt deposition). Causes: choledocholithiasis, cholangiocarcinoma, pancreatic head cancer.', difficulty: 'medium' },
  { id: 'med_8', text: 'Which anti-epileptic drug is CONTRAINDICATED in absence seizures?', options: ['Ethosuximide', 'Valproate', 'Lamotrigine', 'Carbamazepine'], correct: 3, explanation: 'Carbamazepine (and phenytoin) can worsen absence and myoclonic seizures. First-line for absence seizures is ethosuximide or valproate.', difficulty: 'hard' },
  { id: 'med_9', text: 'A patient presents with periorbital edema, proteinuria > 3.5 g/day, hypoalbuminemia, and hyperlipidemia. This is:', options: ['Nephritic syndrome', 'Nephrotic syndrome', 'Acute tubular necrosis', 'Rapidly progressive glomerulonephritis'], correct: 1, explanation: 'Nephrotic syndrome triad: massive proteinuria (>3.5g/day) + hypoalbuminemia + edema + hyperlipidemia + lipiduria. No hematuria/hypertension (unlike nephritic). Most common cause in adults: membranous nephropathy.', difficulty: 'easy' },
  { id: 'med_10', text: 'The classic triad of Cushing\'s syndrome includes:', options: ['Hypotension, weight loss, hyperpigmentation', 'Moon face, central obesity, purple striae', 'Exophthalmos, tremor, heat intolerance', 'Hypocalcemia, tetany, cataracts'], correct: 1, explanation: 'Cushing\'s syndrome (hypercortisolism): moon face, buffalo hump, central obesity, purple abdominal striae, hypertension, hyperglycemia, hirsutism, osteoporosis, and easy bruising.', difficulty: 'easy' },
];

// ============================================================
// SURGERY — Bailey & Love, SRB
// ============================================================
const surgeryMCQs = [
  { id: 'sur_1', text: 'The most common site for carcinoma of the colon is the:', options: ['Ascending colon', 'Transverse colon', 'Descending colon', 'Rectosigmoid junction'], correct: 3, explanation: 'Rectosigmoid junction is the most common site for colorectal carcinoma. Left-sided tumors present with change in bowel habits and obstruction; right-sided present with occult bleeding and anemia.', difficulty: 'medium' },
  { id: 'sur_2', text: 'The diagnostic test of choice for acute appendicitis in a pregnant woman is:', options: ['CT scan abdomen', 'Plain X-ray', 'MRI abdomen', 'Alvarado score clinical diagnosis only'], correct: 2, explanation: 'MRI is the preferred imaging for acute appendicitis in pregnancy (no ionizing radiation risk to fetus). CT is accurate but carries radiation risk. Ultrasound is first-line but limited in pregnancy.', difficulty: 'hard' },
  { id: 'sur_3', text: 'A 45-year-old presents with painless obstructive jaundice, weight loss, and a palpable gallbladder. This is called:', options: ['Charcot\'s triad', 'Courvoisier\'s law', 'Reynolds pentad', 'Murphy\'s sign'], correct: 1, explanation: 'Courvoisier\'s law: a palpable, non-tender gallbladder in the presence of jaundice is unlikely to be due to gallstones (chronic inflammation causes fibrosis). It suggests malignant obstruction (commonly pancreatic head carcinoma).', difficulty: 'medium' },
  { id: 'sur_4', text: 'The most important prognostic factor in breast cancer is:', options: ['Tumor size', 'Lymph node status', 'Histological grade', 'ER/PR receptor status'], correct: 1, explanation: 'Axillary lymph node status (number of involved nodes) is the single most important prognostic factor in breast cancer. Sentinel lymph node biopsy is now standard for clinically node-negative disease.', difficulty: 'medium' },
  { id: 'sur_5', text: 'Virchow\'s triad (risk factors for DVT) consists of:', options: ['Inflammation, infection, immune activation', 'Stasis, endothelial injury, hypercoagulability', 'Obesity, hypertension, diabetes', 'Age, sex, family history'], correct: 1, explanation: 'Virchow\'s triad: (1) venous stasis (immobility, CHF), (2) endothelial injury (trauma, surgery), (3) hypercoagulability (thrombophilia, malignancy, oral contraceptives). All promote DVT formation.', difficulty: 'easy' },
  { id: 'sur_6', text: 'The definitive treatment of choice for perforated duodenal ulcer is:', options: ['Conservative management with IV antibiotics', 'Graham\'s patch repair (omental patch)', 'Gastrectomy', 'Highly selective vagotomy'], correct: 1, explanation: 'Graham\'s omental patch repair is the procedure of choice for perforated duodenal ulcer. The omentum is sutured over the perforation. Definitive anti-ulcer surgery is now rarely needed with effective H. pylori eradication.', difficulty: 'medium' },
  { id: 'sur_7', text: 'In primary survey (ATLS protocol), airway management takes priority. After establishing airway, the next priority is:', options: ['Disability (neurological assessment)', 'Circulation with hemorrhage control', 'Breathing and ventilation', 'Exposure and environment'], correct: 2, explanation: 'ATLS primary survey: A - Airway (with C-spine control), B - Breathing/ventilation, C - Circulation/hemorrhage, D - Disability, E - Exposure. Airway → Breathing → Circulation sequence.', difficulty: 'medium' },
  { id: 'sur_8', text: 'A patient with a stab wound to the chest develops hypotension, distended neck veins, and muffled heart sounds. This triad is called:', options: ['Virchow\'s triad', 'Beck\'s triad (cardiac tamponade)', 'Charcot\'s triad', 'Cushing\'s triad'], correct: 1, explanation: 'Beck\'s triad of cardiac tamponade: (1) hypotension, (2) distended neck veins (JVD), (3) muffled heart sounds. Pulsus paradoxus (>10 mmHg BP drop on inspiration) is also a key sign. Treatment: pericardiocentesis.', difficulty: 'easy' },
  { id: 'sur_9', text: 'What percentage of body surface area (BSA) is attributed to the entire head and neck in the Rule of Nines in adults?', options: ['4.5%', '9%', '18%', '1%'], correct: 1, explanation: 'Rule of Nines (adults): Head and neck = 9%, each upper limb = 9%, chest = 18%, abdomen = 18%, each lower limb = 18%, perineum = 1%. Total = 100%.', difficulty: 'easy' },
  { id: 'sur_10', text: 'The most common type of hernia in females is:', options: ['Inguinal hernia', 'Femoral hernia', 'Umbilical hernia', 'Incisional hernia'], correct: 1, explanation: 'Femoral hernia is more common in females (due to wider female pelvis), though inguinal hernia is more common overall. Femoral hernias have a higher risk of strangulation and require urgent repair.', difficulty: 'medium' },
];

// ============================================================
// PAEDIATRICS — Nelson, Pervaiz Akbar
// ============================================================
const paediatricsMCQs = [
  { id: 'pae_1', text: 'The most common cause of bacterial meningitis in neonates (< 3 months) is:', options: ['Neisseria meningitidis', 'Streptococcus pneumoniae', 'Group B Streptococcus (GBS) and E. coli', 'Haemophilus influenzae'], correct: 2, explanation: 'In neonates, GBS (Streptococcus agalactiae) and E. coli are the most common bacterial causes of meningitis (vertically acquired). Listeria monocytogenes is also important. Treatment: Ampicillin + Gentamicin.', difficulty: 'hard' },
  { id: 'pae_2', text: 'Koplik\'s spots are pathognomonic of:', options: ['Chickenpox (Varicella)', 'Mumps', 'Measles (Rubeola)', 'Rubella'], correct: 2, explanation: 'Koplik\'s spots (white spots with red areola on buccal mucosa opposite lower molars) are pathognomonic of measles. They appear 2-4 days before the maculopapular rash, spreading cephalocaudally.', difficulty: 'easy' },
  { id: 'pae_3', text: 'Normal birth weight is defined as:', options: ['< 2000g', '1500-2000g', '2500-4000g', '> 4000g'], correct: 2, explanation: 'Normal birth weight is 2500-4000g. Low birth weight (LBW) = <2500g, Very LBW = <1500g, Extremely LBW = <1000g. LGA (Large for gestational age) > 4000g (macrosomia).', difficulty: 'easy' },
  { id: 'pae_4', text: 'A child presents with inspiratory stridor, barking cough, and "steeple sign" on X-ray. Diagnosis:', options: ['Acute epiglottitis', 'Croup (laryngotracheobronchitis)', 'Foreign body aspiration', 'Bronchiolitis'], correct: 1, explanation: 'Croup (viral laryngotracheobronchitis): barking/seal-like cough, inspiratory stridor, low-grade fever. X-ray: "steeple sign" (subglottic narrowing). Commonly caused by parainfluenza virus. Treated with dexamethasone ± nebulized epinephrine.', difficulty: 'medium' },
  { id: 'pae_5', text: 'The hallmark triad of child abuse (non-accidental injury) includes:', options: ['Subdural hematoma, retinal hemorrhages, and metaphyseal fractures', 'Subdural hematoma, epidural hematoma, and skull fracture', 'Long bone fractures, bruising, and fever', 'Retinal hemorrhages, CNS infection, and seizures'], correct: 0, explanation: 'Shaken Baby Syndrome/Abusive Head Trauma triad: subdural hematoma + retinal hemorrhages + encephalopathy/metaphyseal (corner/bucket handle) fractures. No external head trauma needed. High suspicion critical.', difficulty: 'hard' },
  { id: 'pae_6', text: 'A 3-month-old baby presents with bilious vomiting and abdominal distension. X-ray shows "double bubble" sign. Diagnosis:', options: ['Pyloric stenosis', 'Malrotation with volvulus', 'Duodenal atresia', 'Hirschsprung\'s disease'], correct: 2, explanation: 'Double bubble sign (two air-fluid levels: stomach + dilated proximal duodenum) is pathognomonic of duodenal atresia. Associated with Down syndrome (trisomy 21) in 30% of cases.', difficulty: 'medium' },
];

// ============================================================
// GYNAECOLOGY/OBSTETRICS — Ten Teachers, DC Dutta
// ============================================================
const gynaecologyMCQs = [
  { id: 'gyn_1', text: 'The most common site of ectopic pregnancy is:', options: ['Ovary', 'Abdominal cavity', 'Ampulla of the fallopian tube', 'Interstitial portion of tube'], correct: 2, explanation: 'Ectopic pregnancy most commonly occurs in the ampulla of the fallopian tube (70%). Other sites: isthmus (12%), fimbria (11%), interstitial (2%), ovary, cervix, abdominal (rare).', difficulty: 'easy' },
  { id: 'gyn_2', text: 'HELLP syndrome in pregnancy stands for:', options: ['Hypertension, Elevated Liver enzymes, Low Platelets, Proteinuria', 'Hemolysis, Elevated Liver enzymes, Low Platelets', 'Hemolysis, Edema, Liver failure, Low Potassium', 'Headache, Elevated LFTs, Low Platelets, Proteinuria'], correct: 1, explanation: 'HELLP = Hemolysis (microangiopathic hemolytic anemia) + Elevated Liver enzymes + Low Platelets. A severe variant of preeclampsia requiring emergency delivery regardless of gestational age.', difficulty: 'medium' },
  { id: 'gyn_3', text: 'The most common cause of postpartum hemorrhage is:', options: ['Retained placenta', 'Uterine rupture', 'Uterine atony', 'Cervical laceration'], correct: 2, explanation: 'Uterine atony (failure of uterus to contract after delivery) is the most common cause of PPH (80%). Management: bimanual uterine compression, oxytocin, misoprostol, ergometrine. "4 T\'s": Tone, Trauma, Tissue, Thrombin.', difficulty: 'easy' },
  { id: 'gyn_4', text: 'A 28-year-old presents with secondary amenorrhea, galactorrhea, and bitemporal hemianopia. Most likely diagnosis:', options: ['PCOS', 'Hypothyroidism', 'Prolactinoma (pituitary adenoma)', 'Sheehans syndrome'], correct: 2, explanation: 'Prolactinoma: amenorrhea + galactorrhea (hyperprolactinemia) + visual field defects (bitemporal hemianopia from optic chiasm compression by macroadenoma). Serum prolactin > 200 ng/mL confirms. Treatment: cabergoline/bromocriptine.', difficulty: 'medium' },
  { id: 'gyn_5', text: 'The Apgar score is assessed at 1 and 5 minutes after birth. Which of the following is NOT included?', options: ['Heart rate', 'Respiratory effort', 'Birth weight', 'Reflex irritability'], correct: 2, explanation: 'Apgar score (0-10): Appearance (color), Pulse (HR), Grimace (reflex), Activity (muscle tone), Respiration. Birth weight is NOT included. Score ≥7 normal, 4-6 moderate depression, <4 severe.', difficulty: 'easy' },
];

// Write all files
const datasets = {
  'anatomy.json': anatomyMCQs,
  'physiology.json': physiologyMCQs,
  'biochemistry.json': biochemistryMCQs,
  'pathology.json': pathologyMCQs,
  'pharmacology.json': pharmacologyMCQs,
  'medicine.json': medicineMCQs,
  'surgery.json': surgeryMCQs,
  'paediatrics.json': paediatricsMCQs,
  'gynaecology.json': gynaecologyMCQs,
};

let totalGenerated = 0;
for (const [filename, data] of Object.entries(datasets)) {
  fs.writeFileSync(path.join(outputDir, filename), JSON.stringify(data, null, 2));
  console.log(`✅ ${filename}: ${data.length} real MCQs generated`);
  totalGenerated += data.length;
}

console.log(`\n🎉 Done! Total MBBS MCQs: ${totalGenerated} real clinical questions`);
